### ISSUE TITLE
Need Lightness/Hue sliders for the colour inputs

### ISSUE THREAD

**Issue by CoreyGinnivan** [CoreyGinnivan/whocanuse#12]

**Comment by jdittrich** [comment]
…is this equivalent to a color selection control, or is _saturation_ excluded for a reason?

**Comment by CoreyGinnivan** [comment]
Can definitely include saturation, was just trying to keep at simple

**Comment by jdittrich** [comment]
Good point, though I guess that most pickers include saturation to be able to define the full spectrum of possible colors, so it will most likely be familiar to people. 

I think of something like [this](https://github.com/Sphinxxxx/vanilla-picker-mini) ([demo](https://codepen.io/d_jan/pen/dyyQgaR))
