### ISSUE TITLE
Having more than 8 or more characters breaks the simulation results

### ISSUE THREAD

**Issue by CoreyGinnivan** [CoreyGinnivan/whocanuse#16]
![Screen Shot 2019-11-20 at 11 28 39 am](https://user-images.githubusercontent.com/7619810/69206864-ea256b00-0b88-11ea-840d-25a153adc9ec.png)

**Comment by MadeByMike** [comment]
@CoreyGinnivan how do you expect this to work? Do you want to limit the characters? That's a quick fix and I'm happy to do it.

**Comment by aesyondu** [comment]
Hey @MadeByMike, how would you do it? I tried adding `maxlength` in background.js and foreground.js but it doesn't seem to work?

```javascript
      <HexWrapper
        type="text"
        name="background"
        textColour={getBackgroundTextColor}
        value={backgroundText}
        maxlength="6"
        onKeyPress={e => {
          if (e.key.match(/[^0-9a-fA-F]/)) {
            e.preventDefault()
          }
        }}
```

**Comment by CoreyGinnivan** [comment]
Don't think a max limit would work, a little hidden feature at the moment is the ability to drop in any colour name or even RGB string, so it'd break that
