### ISSUE TITLE
There a way for another tool to leverage your work?

### ISSUE THREAD

**Issue by argyleink** [CoreyGinnivan/whocanuse#22]
I've got this project https://github.com/GoogleChromeLabs/ProjectVisBug and I'd love to enhance the accessibility hover tooltip with the information your site is currently displaying. 

![Screen Shot 2019-12-06 at 6 56 38 PM](https://user-images.githubusercontent.com/1134620/70367963-69d65980-185a-11ea-8ab4-4720fdf4f9d1.png)

Give it a try by visiting the tool sandbox http://visbug.web.app and picking the accessibility tool from the left toolbar and hovering on things with color you want to compare. Imagine it was that easy to see the information you've uncovered right there in the moment. 

thoughts!?

**Comment by MadeByMike** [comment]
Hi Adam, do you want to do a mock-up of what you are after? I think it would be pretty easy to expose some of this information as a util library.

**Comment by argyleink** [comment]
if i could get json results, i could do better than a mockup, i could deploy a branch! i'm already comparing colors for contrast scores, but i'm not converting to different color blindnesses's and then comparing again. i guess it's not that hard for me to transform the colors in my tool and submit all those transformed sets to the same contrast method.. but i'd love for y'all to get some credit for the idea! 

I dunno, what do you think? How easy would it be for you? I dont want you to do any one off work for me.

**Comment by CoreyGinnivan** [comment]
Might leave this for now as I think it's probably just as easy to use the same library we're tapping in to https://github.com/skratchdot/color-blind/

If we get some more requests we can look in to opening some sort of util library though 🙂I've got no idea how to set that up at the moment, but if someone else wants to jump in then let's do it
