### ISSUE TITLE
Input field text color frequently disobeys WhoCanUse's own color-contrast recommendations

### ISSUE THREAD

**Issue by cartr** [CoreyGinnivan/whocanuse#24]
WhoCanUse sets the text color of its input fields to white on dark backgrounds and black on light backgrounds:

![Screenshot_2019-12-14_18-32-57](https://user-images.githubusercontent.com/5241813/70857284-3b7efc80-1ea0-11ea-9f43-91f05b1ffd77.png)

Hilariously, [the function used for this](https://github.com/CoreyGinnivan/whocanuse/blob/26d9e71082854b0d0e06fc395266b0dfe1a04120/src/components/control/control.js#L12-L25) frequently disagrees with WhoCanUse's own contrast recommendations. In the above example, it placed white text on the #169155, even though WhoCanUse assigns that color combination [a FAIL rating for all but a tiny minority of color-blind users](http://whocanuse.com/?b=169155&c=FFFFFF&f=16&s=b). It should have chosen a black text color --- [that combination gets an AA rating](http://whocanuse.com/?b=169155&c=000000&f=16&s=b).

Personally, I think that the white text is actually a little more readable against the green background than black text. But the whole point of this website is to teach people like me (and the misguided designers who create inaccessible products like [this](https://i.imgur.com/nrXwf3P.jpg)) that we can't rely on our eyes to tell us which color combinations have the best contrast. To maximize accessibility and inclusion, we must defer to the WCAG contrast function, so the input field should use the WCAG contrast function as well.

**Comment by CoreyGinnivan** [comment]
Thanks for the feedback mate, I'm currently looking in to redoing the entire colour pickers setup, so will be taking this in to account.
