### ISSUE TITLE
make font size changes also impact the simulation blocks for vision types

### ISSUE THREAD

**Issue by nagoli** [CoreyGinnivan/whocanuse#25]
Thanks for this great tool 
Would it be possible to control the text size in the simulation blocks on the right (for different vision type) with the size in pixel defined in the left part of the page ? 
thank you

**Comment by CoreyGinnivan** [comment]
No worries mate! The simulations are affected by the font size, there's just so visual indication to suggest it. Shouldn't be too hard to better show that off though.
