### ISSUE TITLE
Avoid back button trap by using `replaceState`

### ISSUE THREAD

**Issue by Paul-Hebert** [CoreyGinnivan/whocanuse#26]
This tool is awesome! Nice work Corey!

I was testing it out and noticed that if you change your colors a number of times, then you have to use the back button an equal number of times to exit back out of the website.

I think it would be better if you only had to use the back button once to exit, regardless of how many changes you'd made.

I think this could be achieved by changing `pushState` to `replaceState` in `updatePath`. If I opened a PR for that would you be open to merging it in? 

Thanks!

**Comment by CoreyGinnivan** [comment]
Hells yeah, let's do it

**Comment by Paul-Hebert** [comment]
Sweet, I'll get started on that! 🤘

**Comment by Paul-Hebert** [comment]
Just opened [a PR](https://github.com/CoreyGinnivan/whocanuse/pull/27)! 😀
