### ISSUE TITLE
Ratio for AAA should be 7:1 rather than 7.5:1

### ISSUE THREAD

**Issue by av1277** [CoreyGinnivan/whocanuse#28]
I love whocanuse and am recommending it to all my contacts.  

I noticed that the threshold for rating AAA appears to be 7.5:1 on whocanuse, instead of 7:1.  According to https://www.w3.org/TR/WCAG21/#contrast-enhanced it is 7.1.

Have I misunderstood?  Or if not could the site be updated to rate >7:1 as AAA?

**Comment by CoreyGinnivan** [comment]
You're absolutely right, no idea how I missed that or when it came in. Just made a PR and it should be all fixed it now :) Let me know if you have anything issues, thanks mate! https://github.com/CoreyGinnivan/whocanuse/pull/29
