### ISSUE TITLE
Inverting colors will replace both colors in querystring with the background color

### ISSUE THREAD

**Issue by arpadgabor** [CoreyGinnivan/whocanuse#38]
Accessing `https://whocanuse.com` and pressing the _invert_ button will invert the colors in the UI, but the URL Querystring will display only the (new) background color: `https://whocanuse.com/?b=ffffff&c=ffffff&f=20&s=`

**Comment by CoreyGinnivan** [comment]
Great pickup, will try and get on to this soon unless someone else can jump in :D
