### ISSUE TITLE
URL parameters are no longer working

### ISSUE THREAD

**Issue by cbirdsong** [CoreyGinnivan/whocanuse#46]
It seems like the form fields are no longer being prefilled from URL parameter values, breaking share links. None of these work for me:

- https://whocanuse.com/?bg=fafafa&fg=246a4e&fs=16&fw=
- https://whocanuse.com/?bg=8e0101&fg=fafafa&fs=18&fw=b

**Comment by CoreyGinnivan** [comment]
Looking in to it, thanks mate 🙏

**Comment by rgembalik** [comment]
@CoreyGinnivan I hope I didn't step on your toes here, but I noticed the same issue and left a PR for it. Feel free to use it or throw it away if it doesn't work for you.

**Comment by CoreyGinnivan** [comment]
@rgembalik Not at all, I appreciate the help 🙏
